### ISSUE TITLE
 Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by harry2011** [SendOTP/SendOTPAndroid#9]
Getting this error on very importing of the project. Can anyone help me in solving this issue.

Thanks in advance.

**Comment by rakshitsoni02** [comment]
This can happen due many reasons generally due to jdk version.

Check your JAVA_HOME to use jdk1.8 Also check : the parameter in Android Studio in order to change at File->Other Settings->Default Project Structure->SDKs 
 OR 
set the version 2.1.0 of gradle to work with Jdk 1.8.0_92 and android studio 2.11

dependencies {

    classpath 'com.android.tools.build:gradle:2.1.0'
    //classpath 'com.android.tools.build:gradle:2.+'
}

OR 
Gradle Scripts >> build.gradle (Module app)

Change buildToolsVersion "24.0.0" to buildToolsVersion "23.0.3"
